import React, { createContext, useContext, useState, useEffect } from 'react';
import { Subaffidamento, Appaltatore, DocumentoControllo, ActivityLog, Settings } from '../types';

interface DataContextType {
  subaffidamenti: Subaffidamento[];
  appaltatori: Appaltatore[];
  documenti: DocumentoControllo[];
  activityLog: ActivityLog[];
  settings: Settings;
  setSubaffidamenti: React.Dispatch<React.SetStateAction<Subaffidamento[]>>;
  setAppaltatori: React.Dispatch<React.SetStateAction<Appaltatore[]>>;
  setDocumenti: React.Dispatch<React.SetStateAction<DocumentoControllo[]>>;
  setActivityLog: React.Dispatch<React.SetStateAction<ActivityLog[]>>;
  setSettings: React.Dispatch<React.SetStateAction<Settings>>;
  addActivity: (tipo: ActivityLog['tipo'], foglio: string, desc: string, detail: string) => void;
}

const DataContext = createContext<DataContextType | undefined>(undefined);

const DEFAULT_SUBAFFIDAMENTI: Subaffidamento[] = [
  {
    id: '28497',
    stato: 'Inviata',
    tipo: 'Subappalto',
    appaltatore: 'PLC SERVICE SRL',
    subfornitore: 'DRONE INSPECTION SERVICE SRL SEMPLIFICATA',
    idSapContratto: '2500043707',
    unitaGestore: 'NE01-O&MS',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'OPERATIONS AND MAINTENANCE IMPIANTI PV',
    dataInizioContratto: '2022-02-01',
    dataFineContratto: '2026-07-31',
    valuta: 'EUR',
    codiceSapAppaltatore: '546837',
    codiceSapSubfornitore: '688767',
    gm: 'SS06BB04',
    descrizioneGm: 'O&M IMPIAN. FOTOVOLT',
    oggettoRichiesta: 'Termografie moduli FTV',
    importoRichiestoValuta: '6,700.00',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'Y',
    ch: 'valentina.cardi@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com',
    dataCreazione: '2026-04-08', inserito: '2026-04-08',
    dataInizio: '2026-04-08', inizio: '2026-04-08',
    dataFine: '2027-04-08', scadenza: '2027-04-08',
    importoRichiestoEuro: '6700', importoEur: '6700',
    importoMassimoSubappaltabile: '2446894', importoMaxSub: '2446894',
    residuoSubappaltabile: '1730288', residuoSub: '1730288',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2026-04-08',
    app: 'PLC SERVICE SRL', sub: 'DRONE INSPECTION SERVICE SRL SEMPLIFICATA',
    idSap: '2500043707', unitaGest: 'NE01-O&MS', socComm: 'NE01',
  },
  {
    id: '28495',
    stato: 'Inviata',
    tipo: 'Subappalto',
    appaltatore: 'ESPE SRL',
    subfornitore: 'S.E.R. SRLS',
    idSapContratto: 'PL25000003',
    unitaGestore: 'NE01-O&MW',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'ATTIVITÀ DI CONDUZIONE E MANUTENZIONE IMPIANTI',
    dataInizioContratto: '2024-07-01',
    dataFineContratto: '2027-06-30',
    valuta: 'EUR',
    codiceSapAppaltatore: '557678',
    codiceSapSubfornitore: '696785',
    gm: 'LL04AD06',
    descrizioneGm: 'ONSHORE WIND FARM',
    oggettoRichiesta: 'RIPRISTINO CAVI - VERGNET CALABRIA',
    importoRichiestoValuta: '4,900.00',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'Y',
    ch: 'gianmaria.sofia@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com, federico.arnone@eni.com, pietro.devito@ren.eniplenitude.com',
    dataCreazione: '2026-04-08', inserito: '2026-04-08',
    dataInizio: '2026-04-13', inizio: '2026-04-13',
    dataFine: '2028-12-31', scadenza: '2028-12-31',
    importoRichiestoEuro: '4900', importoEur: '4900',
    importoMassimoSubappaltabile: '328498', importoMaxSub: '328498',
    residuoSubappaltabile: '308596', residuoSub: '308596',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2026-04-08',
    app: 'ESPE SRL', sub: 'S.E.R. SRLS',
    idSap: 'PL25000003', unitaGest: 'NE01-O&MW', socComm: 'NE01',
  },
  {
    id: '28415',
    stato: 'Inviata',
    tipo: 'Subappalto',
    appaltatore: 'HYDRO ENGINEERING SS DEGLI INGEGNERI DAMIANO E MARIANO GALBO',
    subfornitore: 'GEODET SRL',
    idSapContratto: '2510019412',
    unitaGestore: 'NE01-DEV',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'Servizi di Ingegneria Multidisciplinare',
    dataInizioContratto: '2025-10-13',
    dataFineContratto: '2028-10-12',
    valuta: 'EUR',
    codiceSapAppaltatore: '530421',
    codiceSapSubfornitore: '657850',
    gm: 'SS01BA06',
    descrizioneGm: 'ing imp rinnov',
    oggettoRichiesta: 'TASK 3 - INDAGINI FERROMAGNETICHE',
    importoRichiestoValuta: '8,500.00',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'Y',
    ch: 'alessandro.bartolomei@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'mattia.baroni@ren.eniplenitude.com, manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@external.eni.com, federico.arnone@eni.com',
    dataCreazione: '2026-04-01', inserito: '2026-04-01',
    dataInizio: '2026-04-02', inizio: '2026-04-02',
    dataFine: '2026-08-20', scadenza: '2026-08-20',
    importoRichiestoEuro: '8500', importoEur: '8500',
    importoMassimoSubappaltabile: '223200', importoMaxSub: '223200',
    residuoSubappaltabile: '64995', residuoSub: '64995',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2026-04-03',
    app: 'HYDRO ENGINEERING SS DEGLI INGEGNERI DAMIANO E MARIANO GALBO', sub: 'GEODET SRL',
    idSap: '2510019412', unitaGest: 'NE01-DEV', socComm: 'NE01',
  },
  {
    id: '27938',
    stato: 'In Attesa SAP',
    tipo: 'Subcontratto',
    appaltatore: 'HPC ITALIA SRL',
    subfornitore: "VIGANO' MICHELE",
    idSapContratto: '2510019736',
    unitaGestore: 'NE01-PERM',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'RTI HPC/Montana EPRI',
    dataInizioContratto: '2025-11-19',
    dataFineContratto: '2028-06-18',
    valuta: 'EUR',
    codiceSapAppaltatore: '455002',
    oggettoRichiesta: 'monitoraggio avifauna c/o parco eolico Tarsia',
    importoRichiestoValuta: '16,000.00',
    statoQualifica: 'Not Assigned',
    allegati: 'G',
    protocolloNpa: 'FC2121852',
    esitoProtocolloNpa: 'KO',
    motivazioneProtocollo: 'allegato errato',
    ch: 'carlotta.martignoni@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@external.eni.com, federico.arnone@eni.com',
    dataCreazione: '2026-03-23', inserito: '2026-03-23',
    dataInizio: '2026-03-17', inizio: '2026-03-17',
    dataFine: '2027-03-17', scadenza: '2027-03-17',
    importoRichiestoEuro: '16000', importoEur: '16000',
    importoMassimoSubappaltabile: '1177989', importoMaxSub: '1177989',
    residuoSubappaltabile: '968278', residuoSub: '968278',
    dataUltimoAggiornamento: '2026-03-24',
    app: 'HPC ITALIA SRL', sub: "VIGANO' MICHELE",
    idSap: '2510019736', unitaGest: 'NE01-PERM', socComm: 'NE01',
  },
  {
    id: '27597',
    stato: 'Inviata',
    tipo: 'Subappalto',
    appaltatore: 'HYDRO ENGINEERING SS DEGLI INGEGNERI DAMIANO E MARIANO GALBO',
    subfornitore: 'GEOCIMA SRL',
    idSapContratto: '2510019412',
    unitaGestore: 'NE01-DEV',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'Servizi di Ingegneria Multidisciplinare',
    dataInizioContratto: '2025-10-13',
    dataFineContratto: '2028-10-12',
    valuta: 'EUR',
    codiceSapAppaltatore: '530421',
    codiceSapSubfornitore: '602240',
    gm: 'SS01BA06',
    descrizioneGm: 'ing imp rinnov',
    oggettoRichiesta: 'TASK2 - Indagini geognostiche TASK4 Indagine Georadar',
    importoRichiestoValuta: '149,704.24',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'G',
    ch: 'alessandro.bartolomei@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'mattia.baroni@ren.eniplenitude.com, manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@external.eni.com, federico.arnone@eni.com',
    dataCreazione: '2026-04-01', inserito: '2026-04-01',
    dataInizio: '2026-02-06', inizio: '2026-02-06',
    dataFine: '2026-09-30', scadenza: '2026-09-30',
    importoRichiestoEuro: '149704', importoEur: '149704',
    importoMassimoSubappaltabile: '223200', importoMaxSub: '223200',
    residuoSubappaltabile: '64995', residuoSub: '64995',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2026-04-07',
    app: 'HYDRO ENGINEERING SS DEGLI INGEGNERI DAMIANO E MARIANO GALBO', sub: 'GEOCIMA SRL',
    idSap: '2510019412', unitaGest: 'NE01-DEV', socComm: 'NE01',
  },
  {
    id: '27519',
    stato: 'Scaduta',
    tipo: 'Subappalto',
    appaltatore: 'RINA CONSULTING SPA',
    subfornitore: 'DOTT. ANTONELLO ANGIUS',
    idSapContratto: '2510019410',
    unitaGestore: 'NE01-DEV',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'Servizi di Ingegneria Multidisciplinare',
    dataInizioContratto: '2025-10-13',
    dataFineContratto: '2028-10-12',
    valuta: 'EUR',
    codiceSapAppaltatore: '354750',
    codiceSapSubfornitore: '645901',
    gm: 'SS01BA06',
    descrizioneGm: 'ing imp rinnov',
    oggettoRichiesta: 'Esecuzione indagini geognostiche - Porto Torres e Sarroch',
    importoRichiestoValuta: '6,779.62',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'G',
    ch: 'alessandro.bartolomei@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'mattia.baroni@ren.eniplenitude.com, manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@external.eni.com, federico.arnone@eni.com',
    dataCreazione: '2026-02-13', inserito: '2026-02-13',
    dataInizio: '2026-01-29', inizio: '2026-01-29',
    dataFine: '2026-03-31', scadenza: '2026-03-31',
    importoRichiestoEuro: '6779', importoEur: '6779',
    importoMassimoSubappaltabile: '529200', importoMaxSub: '529200',
    residuoSubappaltabile: '448743', residuoSub: '448743',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2026-03-31',
    app: 'RINA CONSULTING SPA', sub: 'DOTT. ANTONELLO ANGIUS',
    idSap: '2510019410', unitaGest: 'NE01-DEV', socComm: 'NE01',
  },
  {
    id: '27517',
    stato: 'Inviata',
    tipo: 'Subappalto',
    appaltatore: 'RINA CONSULTING SPA',
    subfornitore: 'DL DRONI SRL',
    idSapContratto: '2510019410',
    unitaGestore: 'NE01-DEV',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'Servizi di Ingegneria Multidisciplinare',
    dataInizioContratto: '2025-10-13',
    dataFineContratto: '2028-10-12',
    valuta: 'EUR',
    codiceSapAppaltatore: '354750',
    codiceSapSubfornitore: '609045',
    gm: 'SS01BA06',
    descrizioneGm: 'ing imp rinnov',
    oggettoRichiesta: 'LiDAR Rilievo Topografico BESS Porto Torres e Sarroch',
    importoRichiestoValuta: '8,299.75',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'Y',
    protocolloNpa: 'FC2108519',
    esitoProtocolloNpa: 'OK',
    ch: 'alessandro.bartolomei@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'mattia.baroni@ren.eniplenitude.com, manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@external.eni.com, federico.arnone@eni.com',
    dataCreazione: '2026-02-13', inserito: '2026-02-13',
    dataInizio: '2026-01-29', inizio: '2026-01-29',
    dataFine: '2026-03-31', scadenza: '2026-03-31',
    importoRichiestoEuro: '8299', importoEur: '8299',
    importoMassimoSubappaltabile: '529200', importoMaxSub: '529200',
    residuoSubappaltabile: '448743', residuoSub: '448743',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2026-03-23',
    app: 'RINA CONSULTING SPA', sub: 'DL DRONI SRL',
    idSap: '2510019410', unitaGest: 'NE01-DEV', socComm: 'NE01',
  },
  {
    id: '27257',
    stato: 'Inviata',
    tipo: 'Subappalto',
    appaltatore: 'SICURITALIA SPA',
    subfornitore: 'RANGERS SRL',
    idSapContratto: '2510019541',
    unitaGestore: 'NE01-O&MSUP',
    unitaProcuratore: 'AD-EP/GPRO/RMSP',
    societaCommittente: 'NE01',
    oggetto: 'SERV. VIG. E PORT._LOMBARDIA_NE01',
    dataInizioContratto: '2023-02-01',
    dataFineContratto: '2028-01-31',
    valuta: 'EUR',
    codiceSapAppaltatore: '420300',
    codiceSapSubfornitore: '422993',
    gm: 'SS11BB03',
    descrizioneGm: 'VIGILANZA/GUARD',
    oggettoRichiesta: 'SUBAPPALTO RANGERS SRL - SITI DI AVIO E CAVALLERIZZA (AL)',
    importoRichiestoValuta: '17,500.00',
    statoQualifica: 'Q — Qualified',
    statoAnagrafica: '0 — Open',
    allegati: 'G',
    ch: 'dario.defrancesco@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'stefano.passini@ren.eniplenitude.com, manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com, federico.arnone@eni.com',
    dataCreazione: '2026-02-19', inserito: '2026-02-19',
    dataInizio: '2026-01-28', inizio: '2026-01-28',
    dataFine: '2027-05-31', scadenza: '2027-05-31',
    importoRichiestoEuro: '17500', importoEur: '17500',
    importoMassimoSubappaltabile: '106464', importoMaxSub: '106464',
    residuoSubappaltabile: '76574', residuoSub: '76574',
    statoPerProvvedimento: '1 — Active with monitoring', statoProv: '1 — Active with monitoring',
    dataUltimoAggiornamento: '2026-02-26',
    app: 'SICURITALIA SPA', sub: 'RANGERS SRL',
    idSap: '2510019541', unitaGest: 'NE01-O&MSUP', socComm: 'NE01',
  },
  {
    id: '27068',
    stato: 'Inviata',
    tipo: 'Subappalto',
    appaltatore: 'DUSSMANN SERVICE SRL',
    subfornitore: 'TALOZZI IMPIANTI DI TALOZZI GIUSEPPE',
    idSapContratto: '2510019710',
    unitaGestore: 'NE01-HRNE',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'GLOBAL SERVICE - CESENA e CORTALE',
    dataInizioContratto: '2025-12-01',
    dataFineContratto: '2028-12-01',
    valuta: 'EUR',
    codiceSapAppaltatore: '124466',
    codiceSapSubfornitore: '572017',
    gm: 'SS11AB07',
    descrizioneGm: 'SERVIZI DI GESTIONE',
    oggettoRichiesta: 'Esecuzione Servizi di Global Service',
    importoRichiestoValuta: '7,000.00',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'Y',
    ch: 'Daniela.Pellicano@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    dataCreazione: '2026-02-10', inserito: '2026-02-10',
    dataInizio: '2026-01-19', inizio: '2026-01-19',
    dataFine: '2026-05-31', scadenza: '2026-05-31',
    importoRichiestoEuro: '7000', importoEur: '7000',
    importoMassimoSubappaltabile: '904000', importoMaxSub: '904000',
    residuoSubappaltabile: '777360', residuoSub: '777360',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2026-03-18',
    app: 'DUSSMANN SERVICE SRL', sub: 'TALOZZI IMPIANTI DI TALOZZI GIUSEPPE',
    idSap: '2510019710', unitaGest: 'NE01-HRNE', socComm: 'NE01',
  },
  {
    id: '26979',
    stato: 'Scaduta',
    tipo: 'Subappalto',
    appaltatore: 'SICURITALIA SPA',
    subfornitore: 'M. & V. SICUREZZA DI MONTANARI VITTORIO E VALVO DAVIDE & C. SAS',
    idSapContratto: '2510019541',
    unitaGestore: 'NE01-O&MSUP',
    unitaProcuratore: 'AD-EP/GPRO/RMSP',
    societaCommittente: 'NE01',
    oggetto: 'SERV. VIG. E PORT._LOMBARDIA_NE01',
    dataInizioContratto: '2023-02-01',
    dataFineContratto: '2028-01-31',
    valuta: 'EUR',
    codiceSapAppaltatore: '420300',
    codiceSapSubfornitore: '573059',
    gm: 'SS11BB01',
    descrizioneGm: 'SERV ING. X SECURITY',
    oggettoRichiesta: 'Centralizzazione impianto antifurto e tvcc',
    importoRichiestoValuta: '7,700.00',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'G',
    ch: 'dario.defrancesco@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, rosalinda.difiore@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'stefano.passini@ren.eniplenitude.com, manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com, federico.arnone@eni.com',
    dataCreazione: '2026-01-12', inserito: '2026-01-12',
    dataInizio: '2026-01-19', inizio: '2026-01-19',
    dataFine: '2026-01-31', scadenza: '2026-01-31',
    importoRichiestoEuro: '7700', importoEur: '7700',
    importoMassimoSubappaltabile: '106464', importoMaxSub: '106464',
    residuoSubappaltabile: '76574', residuoSub: '76574',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2026-01-31',
    app: 'SICURITALIA SPA', sub: 'M. & V. SICUREZZA DI MONTANARI VITTORIO E VALVO DAVIDE & C. SAS',
    idSap: '2510019541', unitaGest: 'NE01-O&MSUP', socComm: 'NE01',
  },
  {
    id: '23276',
    stato: 'Scaduta',
    tipo: 'Subappalto',
    appaltatore: 'TERNA ENERGY SOLUTIONS SRL',
    subfornitore: 'AR.DE. ANTINCENDIO SRL',
    idSapContratto: '3500053338',
    unitaGestore: 'NE01-PEX',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'EPC STORAGE ASSEMINI',
    dataInizioContratto: '2021-04-29',
    valuta: 'EUR',
    codiceSapAppaltatore: '534791',
    codiceSapSubfornitore: '511599',
    gm: 'SS12AA01',
    descrizioneGm: 'O&M SERVICES',
    oggettoRichiesta: 'Manutenzione programmata e correttiva sistemi antincendio',
    importoRichiestoValuta: '1.00',
    statoQualifica: 'Not Assigned',
    allegati: 'G',
    ch: 'Fabiana.Zangheri@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com',
    dataCreazione: '2025-04-08', inserito: '2025-04-08',
    dataInizio: '2025-03-07', inizio: '2025-03-07',
    dataFine: '2025-12-31', scadenza: '2025-12-31',
    importoRichiestoEuro: '1', importoEur: '1',
    importoMassimoSubappaltabile: '1971656', importoMaxSub: '1971656',
    residuoSubappaltabile: '1439610', residuoSub: '1439610',
    dataUltimoAggiornamento: '2025-12-31',
    app: 'TERNA ENERGY SOLUTIONS SRL', sub: 'AR.DE. ANTINCENDIO SRL',
    idSap: '3500053338', unitaGest: 'NE01-PEX', socComm: 'NE01',
  },
  {
    id: '23177',
    stato: 'Scaduta',
    tipo: 'Subappalto',
    appaltatore: 'TERNA ENERGY SOLUTIONS SRL',
    subfornitore: 'AILUX S.R.L.',
    idSapContratto: '3500053338',
    unitaGestore: 'NE01-PEX',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'EPC STORAGE ASSEMINI',
    dataInizioContratto: '2021-04-29',
    valuta: 'EUR',
    codiceSapAppaltatore: '534791',
    codiceSapSubfornitore: '446912',
    gm: 'SS12AA01',
    descrizioneGm: 'O&M SERVICES',
    oggettoRichiesta: 'Manutenzione sistemi Ailux UVRF',
    importoRichiestoValuta: '1.00',
    statoQualifica: 'Not Assigned',
    allegati: 'G',
    ch: 'Fabiana.Zangheri@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com',
    dataCreazione: '2025-04-02', inserito: '2025-04-02',
    dataInizio: '2025-03-14', inizio: '2025-03-14',
    dataFine: '2026-03-14', scadenza: '2026-03-14',
    importoRichiestoEuro: '1', importoEur: '1',
    importoMassimoSubappaltabile: '1971656', importoMaxSub: '1971656',
    residuoSubappaltabile: '1439610', residuoSub: '1439610',
    dataUltimoAggiornamento: '2026-03-14',
    app: 'TERNA ENERGY SOLUTIONS SRL', sub: 'AILUX S.R.L.',
    idSap: '3500053338', unitaGest: 'NE01-PEX', socComm: 'NE01',
  },
  {
    id: '22845',
    stato: 'Inviata',
    tipo: 'Subappalto',
    appaltatore: 'TERNA ENERGY SOLUTIONS SRL',
    subfornitore: 'CESI SPA',
    idSapContratto: '3500053338',
    unitaGestore: 'NE01-PEX',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'EPC STORAGE ASSEMINI',
    dataInizioContratto: '2021-04-29',
    valuta: 'EUR',
    codiceSapAppaltatore: '534791',
    codiceSapSubfornitore: '104290',
    gm: 'SS12AA01',
    descrizioneGm: 'O&M SERVICES',
    oggettoRichiesta: 'Prove di conformità Adeguamento Allegato A79',
    importoRichiestoValuta: '48,375.00',
    statoQualifica: 'Not Assigned',
    allegati: 'R',
    ch: 'Fabiana.Zangheri@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com',
    dataCreazione: '2025-03-19', inserito: '2025-03-19',
    dataInizio: '2025-03-20', inizio: '2025-03-20',
    dataFine: '2025-12-31', scadenza: '2025-12-31',
    importoRichiestoEuro: '48375', importoEur: '48375',
    importoMassimoSubappaltabile: '1971656', importoMaxSub: '1971656',
    residuoSubappaltabile: '1439610', residuoSub: '1439610',
    dataUltimoAggiornamento: '2025-06-06',
    app: 'TERNA ENERGY SOLUTIONS SRL', sub: 'CESI SPA',
    idSap: '3500053338', unitaGest: 'NE01-PEX', socComm: 'NE01',
  },
  {
    id: '22835',
    stato: 'Scaduta',
    tipo: 'Subappalto',
    appaltatore: 'TERNA ENERGY SOLUTIONS SRL',
    subfornitore: 'SICON SRL',
    idSapContratto: '3500053338',
    unitaGestore: 'NE01-PEX',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'EPC STORAGE ASSEMINI',
    dataInizioContratto: '2021-04-29',
    valuta: 'EUR',
    codiceSapAppaltatore: '534791',
    codiceSapSubfornitore: '120773',
    gm: 'SS12AA01',
    descrizioneGm: 'O&M SERVICES',
    oggettoRichiesta: 'Manutenzione UPS',
    importoRichiestoValuta: '1,300.00',
    statoQualifica: 'Not Assigned',
    allegati: 'G',
    ch: 'Fabiana.Zangheri@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com',
    dataCreazione: '2025-03-19', inserito: '2025-03-19',
    dataInizio: '2025-03-31', inizio: '2025-03-31',
    dataFine: '2025-12-31', scadenza: '2025-12-31',
    importoRichiestoEuro: '1300', importoEur: '1300',
    importoMassimoSubappaltabile: '1971656', importoMaxSub: '1971656',
    residuoSubappaltabile: '1439610', residuoSub: '1439610',
    dataUltimoAggiornamento: '2025-12-31',
    app: 'TERNA ENERGY SOLUTIONS SRL', sub: 'SICON SRL',
    idSap: '3500053338', unitaGest: 'NE01-PEX', socComm: 'NE01',
  },
  {
    id: '20033',
    stato: 'Scaduta',
    tipo: 'Subappalto',
    appaltatore: 'TERNA ENERGY SOLUTIONS SRL',
    subfornitore: 'SCHWEITZER ENGINEERING LABORATORIES SRL',
    idSapContratto: '3500053338',
    unitaGestore: 'NE01-PEX',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'EPC STORAGE ASSEMINI',
    dataInizioContratto: '2021-04-29',
    valuta: 'EUR',
    codiceSapAppaltatore: '534791',
    codiceSapSubfornitore: '655421',
    gm: 'LL04AD08',
    descrizioneGm: 'BATTERY ENERGY STORAGE SYSTEM',
    oggettoRichiesta: 'Fornitura e configurazione PMU',
    importoRichiestoValuta: '10,995.22',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'G',
    ch: 'Fabiana.Zangheri@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com',
    dataCreazione: '2024-09-11', inserito: '2024-09-11',
    dataInizio: '2024-10-02', inizio: '2024-10-02',
    dataFine: '2024-12-31', scadenza: '2024-12-31',
    importoRichiestoEuro: '10995', importoEur: '10995',
    importoMassimoSubappaltabile: '1971656', importoMaxSub: '1971656',
    residuoSubappaltabile: '1439610', residuoSub: '1439610',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2024-12-31',
    app: 'TERNA ENERGY SOLUTIONS SRL', sub: 'SCHWEITZER ENGINEERING LABORATORIES SRL',
    idSap: '3500053338', unitaGest: 'NE01-PEX', socComm: 'NE01',
  },
  {
    id: '17689',
    stato: 'Scaduta',
    tipo: 'Subappalto',
    appaltatore: 'TERNA ENERGY SOLUTIONS SRL',
    subfornitore: 'AR.DE. ANTINCENDIO SRL',
    idSapContratto: '3500053338',
    unitaGestore: 'NE01-PEX',
    unitaProcuratore: 'AD-EP/GPRO/RENPR',
    societaCommittente: 'NE01',
    oggetto: 'EPC STORAGE ASSEMINI',
    dataInizioContratto: '2021-04-29',
    valuta: 'EUR',
    codiceSapAppaltatore: '534791',
    codiceSapSubfornitore: '511599',
    gm: 'LL04AD07',
    descrizioneGm: 'SISTEMA DI ACCUMULO GRID SCALE',
    oggettoRichiesta: 'Manutenzione Antincendio',
    importoRichiestoValuta: '1,200.00',
    statoQualifica: 'Not Assigned',
    statoAnagrafica: '0 — Open',
    allegati: 'G',
    ch: 'Fabiana.Zangheri@ren.eniplenitude.com',
    cam: 'Vittorio.Longo@eniplenitude.com',
    chc: 'federica.damato@ren.eniplenitude.com, antoninoangelo.polito@ren.eniplenitude.com, pietro.devito@ren.eniplenitude.com',
    cc: 'manuela.aiolfi@ren.eniplenitude.com, mariaceleste.martellotti@eni.com',
    dataCreazione: '2024-04-16', inserito: '2024-04-16',
    dataInizio: '2024-06-14', inizio: '2024-06-14',
    dataFine: '2024-12-31', scadenza: '2024-12-31',
    importoRichiestoEuro: '1200', importoEur: '1200',
    importoMassimoSubappaltabile: '1971656', importoMaxSub: '1971656',
    residuoSubappaltabile: '1439610', residuoSub: '1439610',
    statoPerProvvedimento: '0 — Active', statoProv: '0 — Active',
    dataUltimoAggiornamento: '2024-12-31',
    app: 'TERNA ENERGY SOLUTIONS SRL', sub: 'AR.DE. ANTINCENDIO SRL',
    idSap: '3500053338', unitaGest: 'NE01-PEX', socComm: 'NE01',
  },
];

const DEFAULT_APPALTATORI: Appaltatore[] = [
  { nome: 'DUSSMANN SERVICE SRL', settore: 'Servizi', tipo: 'Azienda', referente: '', email: '', tel: '', piva: '', sede: '', note: '', aggiunto: '2024-01-01' },
  { nome: 'ESPE SRL', settore: 'Energia', tipo: 'Azienda', referente: '', email: '', tel: '', piva: '', sede: '', note: '', aggiunto: '2024-01-01' },
  { nome: 'HPC ITALIA SRL', settore: 'Ingegneria', tipo: 'Azienda', referente: '', email: '', tel: '', piva: '', sede: '', note: '', aggiunto: '2024-01-01' },
  { nome: 'HYDRO ENGINEERING SS DEGLI INGEGNERI DAMIANO E MARIANO GALBO', settore: 'Ingegneria', tipo: 'Azienda', referente: '', email: '', tel: '', piva: '', sede: '', note: '', aggiunto: '2024-01-01' },
  { nome: 'PLC SERVICE SRL', settore: 'Energia', tipo: 'Azienda', referente: '', email: '', tel: '', piva: '', sede: '', note: '', aggiunto: '2024-01-01' },
  { nome: 'RINA CONSULTING SPA', settore: 'Ingegneria', tipo: 'Azienda', referente: '', email: '', tel: '', piva: '', sede: '', note: '', aggiunto: '2024-01-01' },
  { nome: 'SICURITALIA SPA', settore: 'Sicurezza', tipo: 'Azienda', referente: '', email: '', tel: '', piva: '', sede: '', note: '', aggiunto: '2024-01-01' },
  { nome: 'TERNA ENERGY SOLUTIONS SRL', settore: 'Energia', tipo: 'Azienda', referente: '', email: '', tel: '', piva: '', sede: '', note: '', aggiunto: '2024-01-01' },
];

export const DataProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const pLoad = (key: string, def: any) => {
    const saved = localStorage.getItem(key);
    return saved ? JSON.parse(saved) : def;
  };

  const pSave = (key: string, val: any) => {
    localStorage.setItem(key, JSON.stringify(val));
  };

  const [subaffidamenti, setSubaffidamenti] = useState<Subaffidamento[]>(() => pLoad('subdata', DEFAULT_SUBAFFIDAMENTI));
  const [appaltatori, setAppaltatori] = useState<Appaltatore[]>(() => pLoad('anagrafica', DEFAULT_APPALTATORI));
  const [documenti, setDocumenti] = useState<DocumentoControllo[]>(() => pLoad('docdata', []));
  const [activityLog, setActivityLog] = useState<ActivityLog[]>(() => pLoad('activity_log', []));
  const [settings, setSettings] = useState<Settings>(() => pLoad('settings', {
    accent_color: '#534AB7',
    density: 'normal',
    animations: true,
    tooltips: true,
    alert_scadenze: true,
    alert_days: 30,
    alert_rigettate: true,
    alert_documenti: true,
    cal_auto: true,
    cal_default_view: 'today',
    import_dup_default: 'ask',
    import_preview: true,
    import_log: true,
    standby_enabled: true,
    standby_minutes: 15
  }));

  useEffect(() => pSave('subdata', subaffidamenti), [subaffidamenti]);
  useEffect(() => pSave('anagrafica', appaltatori), [appaltatori]);
  useEffect(() => pSave('docdata', documenti), [documenti]);
  useEffect(() => pSave('activity_log', activityLog), [activityLog]);
  useEffect(() => pSave('settings', settings), [settings]);

  const addActivity = (tipo: ActivityLog['tipo'], foglio: string, desc: string, detail: string) => {
    const user = JSON.parse(localStorage.getItem('pser_current_user') || '{"nome":"Sistema"}');
    const now = new Date();
    const newLog: ActivityLog = {
      ts: now.toISOString(),
      tsDisplay: now.toLocaleString('it-IT'),
      utente: user.nome,
      tipo,
      foglio,
      desc,
      detail
    };
    setActivityLog(prev => [newLog, ...prev].slice(0, 500));
  };

  return (
    <DataContext.Provider value={{
      subaffidamenti, appaltatori, documenti, activityLog, settings,
      setSubaffidamenti, setAppaltatori, setDocumenti, setActivityLog, setSettings,
      addActivity
    }}>
      {children}
    </DataContext.Provider>
  );
};

export const useData = () => {
  const context = useContext(DataContext);
  if (context === undefined) {
    throw new Error('useData must be used within a DataProvider');
  }
  return context;
};
